### ISSUE TITLE
checking nested lists and internal markup in list text

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#50] opened 2018-09-20 04:17 UTC
check lists which had problem ( Issue #4 )
- [ ] amss
- [x] amss2
- [x] amss3
- [x] arellano
- [x] calvo
- [x] career
- [ ] chang_credible
- [x] discrete_dp
- [x] dyn_stack
- [x] getting_started
- [x] jv
- [x] kalman
- [x] linear_models
- [x] lqcontrol
- [x] lqramsey
- [x] lu_tricks
- [x] lucas_model
- [x] markov_perf
- [x] multiplicative_functionals
- [ ] opt_tax_recur
- [x] optgrowth
- [x] orth_proj
- [x] pandas
- [x] perm_income
- [x] perm_income_cons
- [ ] python_advanced_features
- [x] python_by_example
- [x] python_essentials
- [x] python_oop
- [x] rational_expectations
- [x] rob_markov_perf
- [x] robustness
- [x] scipy
- [x] smoothing
- [x] stationary_densities

**Comment by fkazemian** [comment] 2018-09-20 05:14
arellano was 
![45006162-e0265380-b03a-11e8-98c4-f6c8a0b036b1](https://user-images.githubusercontent.com/20714542/45797187-b1b9a100-bce7-11e8-8fde-04964a071b40.png)

![45006167-e4eb0780-b03a-11e8-86b6-b353a4c2d7fd](https://user-images.githubusercontent.com/20714542/45797188-b1b9a100-bce7-11e8-88fe-fe8f12b9b53d.png)

the first one fixed but the second one is
![screenshot from 2018-09-20 15-12-12](https://user-images.githubusercontent.com/20714542/45797205-c9912500-bce7-11e8-81a4-cae1c5f4517a.png)

**Comment by mmcky** [comment] 2018-09-20 05:17
thanks @fkazemian it looks like I've messed up the list construct when trying to add index support.

**Comment by fkazemian** [comment] 2018-09-20 05:18
chang_credible was 
![1](https://user-images.githubusercontent.com/20714542/45797348-6f449400-bce8-11e8-9fd4-19784adef5bb.png)

![2](https://user-images.githubusercontent.com/20714542/45797352-710e5780-bce8-11e8-915f-d397187791db.png)

the first one fixed but the second one is:
![screenshot from 2018-09-20 15-17-15](https://user-images.githubusercontent.com/20714542/45797357-79ff2900-bce8-11e8-8c44-5d37a23c7365.png)

**Comment by mmcky** [comment] 2018-09-20 05:32
hi @fkazemian the instance has been updated without ``index`` support. Can you check those cases you found above and let me know if they have been fixed by adding a comment to each. Thanks!

**Comment by fkazemian** [comment] 2018-09-20 05:37
@mmcky I just checked, as you can see bellow arellano is fixed:

![screenshot from 2018-09-20 15-35-12](https://user-images.githubusercontent.com/20714542/45797880-0dd1f480-bceb-11e8-9da6-2344d33f1345.png)

but the others not, for example amss:
![screenshot from 2018-09-20 15-35-50](https://user-images.githubusercontent.com/20714542/45797902-2215f180-bceb-11e8-976e-2d5df91709c7.png)

**Comment by fkazemian** [comment] 2018-09-20 05:50
opt_tax_recur
multi-level lists are fixed but those one with numerical index have still some problem:

![screenshot from 2018-09-20 15-32-57](https://user-images.githubusercontent.com/20714542/45798334-e1b77300-bcec-11e8-8f29-17c3ba7d21ff.png)


![screenshot from 2018-09-20 15-32-29](https://user-images.githubusercontent.com/20714542/45798335-e1b77300-bcec-11e8-87c8-8e8adc9f02e9.png)

**Comment by fkazemian** [comment] 2018-09-20 05:52
If we want to be too strict, optgrowth is:
![screenshot from 2018-09-20 15-51-37](https://user-images.githubusercontent.com/20714542/45798419-30650d00-bced-11e8-9a74-37024076d660.png)
but I suppose there is no problem, so I checked it as fixed

**Comment by mmcky** [comment] 2018-09-20 05:56
I think I know what the problem is with `index` support. I will work on a fix now. 

Can you post the source for `optgrowth`?

**Comment by fkazemian** [comment] 2018-09-20 06:01
@mmcky , `optgrowth` is a list here. the code for  is 
```
In our setting, we have the following key result

    * A feasible consumption policy is optimal if and only import numpy as np

```

**Comment by fkazemian** [comment] 2018-09-20 06:05
python_advanced_features:    (I'll check it, I think the problem is related to `rst` )
![screenshot from 2018-09-20 16-03-36](https://user-images.githubusercontent.com/20714542/45798903-f432ac00-bcee-11e8-8c5e-b8ac5a7f6a88.png)

**Comment by fkazemian** [comment] 2018-09-20 06:09
for python_by_example, all of them are fixed, but I think this list is not beautiful which has 1, 2 and again 1,2, anyway it is fixed.

![screenshot from 2018-09-20 16-06-58](https://user-images.githubusercontent.com/20714542/45799044-80dd6a00-bcef-11e8-8189-ec788dc5e80f.png)

**Comment by mmcky** [comment] 2018-09-20 09:31
- [ ] compare-lectures has been updated with all the fixes discussed above

**Comment by mmcky** [comment] 2018-09-21 05:08
@fkazemian would you mind checking these issues on the latest set of files on compare?

**Comment by fkazemian** [comment] 2018-09-21 06:07
Hi @mmcky , sure

- [ ] amss
- [ ] amss2
- [ ] amss3
- [ ] arellano
- [ ] calvo
- [ ] career
- [ ] chang_credible
- [ ] discrete_dp
- [ ] dyn_stack
- [ ] getting_started
- [ ] jv
- [ ] kalman
- [ ] linear_models
- [ ] lqcontrol
- [ ] lqramsey
- [ ] lu_tricks
- [ ] lucas_model
- [ ] markov_perf
- [ ] multiplicative_functionals
- [ ] opt_tax_recur
- [ ] optgrowth
- [ ] orth_proj
- [ ] pandas
- [ ] perm_income
- [ ] perm_income_cons
- [ ] python_advanced_features
- [ ] python_by_example
- [ ] python_essentials
- [ ] python_oop
- [ ] rational_expectations
- [ ] rob_markov_perf
- [ ] robustness
- [ ] scipy
- [ ] smoothing
- [ ] stationary_densities

**Comment by fkazemian** [comment] 2018-09-21 06:50
amss is like 
![screenshot from 2018-09-21 16-09-26](https://user-images.githubusercontent.com/20714542/45863282-ca45bc00-bdb8-11e8-9d60-b2d16edb7c32.png)

but I mark it as fixed.

chang_credible
![screenshot from 2018-09-21 16-17-38](https://user-images.githubusercontent.com/20714542/45863546-f1e95400-bdb9-11e8-8df3-adb70adb4f8b.png)

opt_tax_recur is like 
![screenshot from 2018-09-21 16-46-20](https://user-images.githubusercontent.com/20714542/45864631-f283e980-bdbd-11e8-869e-4c4eabec3a9e.png)
I marked it as fixed.

**Comment by fkazemian** [comment] 2018-09-21 07:01
python_oop
it seems code is not supported in nested lists:
![screenshot from 2018-09-21 16-54-05](https://user-images.githubusercontent.com/20714542/45865097-b81b4c00-bdbf-11e8-9ebb-1cd400ce6518.png)

code:
```
* Any instance data should be prepended with `self`

    * e.g., the `earn` method references `self.wealth` rather than just `wealth`

* Any method defined within the class should have `self` as its first argument

    * e.g., `def earn(self, y)` rather than just `def earn(y)`

* Any method referenced within the class should be called as  `self.method_name`

```

**Comment by fkazemian** [comment] 2018-09-21 07:14
Hi @mmcky I fixed the problem for chang_credible in PR  #56

**Comment by fkazemian** [comment] 2018-09-21 07:15
The only problem as you can see is supporting code inside of lists, if we don't attention to that here I have to tell this issue is fixed. I change the label to question and fixed.

**Comment by mmcky** [comment] 2018-11-08 04:39
@natashawatkins for ``python_oop`` example listed above. It appears that many of the items are using a single quote. Do you agree they should be double single quotes (http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)?

**Comment by natashawatkins** [comment] 2018-11-12 03:07
Are you referring to the highlighting? I think throughout most of the lecture's we've used single quotes  - why doesn't this work when the notebook is compiled from rst?

**Comment by mmcky** [comment] 2018-11-26 05:02
@natashawatkins have these been fixed?

**Comment by natashawatkins** [comment] 2018-11-26 05:03
Ah, I don't believe so - I've done a few lectures related to jit but not the above one

**Comment by mmcky** [comment] 2018-11-27 04:48
once you have -- can you close this issue? Thanks.

**Comment by mmcky** [comment] 2019-01-25 01:55
the ``python_oop`` nested lists look fine now.

**Closed by mmcky** 2019-01-25 01:55 UTC
Labels: bug
