### ISSUE TITLE
It seems Jupinx  has problem with some math blocks - inside tables

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#8] opened 2018-08-28 06:37 UTC
![5](https://user-images.githubusercontent.com/20714542/44704961-8bd21f80-aae0-11e8-9090-ac57cc9c5270.png)

**Comment by fkazemian** [comment] 2018-08-28 06:41
It seems it has problem with {bmatrix} 
![6](https://user-images.githubusercontent.com/20714542/44705192-4104d780-aae1-11e8-895c-29713195fee0.png)

**Comment by mmcky** [comment] 2018-08-30 06:29
thanks @fkazemian `bmatrix` is working in some cases and not in others.
Can you please update these with references to which lecture the screenshots came from? Thanks.

**Comment by mmcky** [comment] 2018-08-30 06:29
mathjax itself supports `bmatrix` so I suspect some of this is incorrect source in the RST

**Comment by fkazemian** [comment] 2018-09-04 01:47
![1](https://user-images.githubusercontent.com/20714542/45005674-20d09d80-b038-11e8-8cca-31948971a39b.png)

(arellano)- The code is

```
.. math::

    v_d(y) = u(h(y))
        + \beta \int \left\{
                \theta v(0, y') + (1 - \theta) v_d(y')
                \right\}
                p(y, y') dy'


The value of paying is

.. math::

    v_c(B, y) = \max_{B' \geq -Z}
           \left\{
                u(y - q(B', y) B' + B)
                + \beta \int v(B', y') p(y, y') dy'
          \right\}
```

**Comment by fkazemian** [comment] 2018-09-04 06:57
(calvo) 
![screenshot from 2018-09-04 16-36-10](https://user-images.githubusercontent.com/20714542/45014787-0e1f8e00-b063-11e8-8942-be136b93a813.png)

code 
```
.. math::
    :label: eq_old9

    \theta_0 & = \theta_0^* \\
    \mu_t &  = b_0 + b_1 \theta_t \\
    \theta_{t+1} & = d_0 + d_1 \theta_t
```
![screenshot from 2018-09-04 16-37-11](https://user-images.githubusercontent.com/20714542/45014861-3effc300-b063-11e8-897d-7322ec99debb.png)

code
`.. math::  - \frac{\alpha}{1+\alpha} a_1 - a_2(-\frac{\alpha^2}{1+\alpha} \bar \mu - \frac{\alpha}{1+\alpha} \mu_t)(- \frac{\alpha}{1+\alpha}) - c \mu_t = 0`

![screenshot from 2018-09-04 16-39-19](https://user-images.githubusercontent.com/20714542/45014906-635b9f80-b063-11e8-9a47-99f03db986e8.png)

code
```
.. math::
    :label: eq_old10

    v_j^A & = s(\theta^A_j, \mu^A_j) + \beta v_{j+1}^A \\
    & \geq s(\theta^A_j, 0 ) + \beta v_0^A \equiv v_j^{A,D}, \quad j \geq 0

```

![screenshot from 2018-09-04 16-39-28](https://user-images.githubusercontent.com/20714542/45014944-7ff7d780-b063-11e8-8953-c54bf027b7f9.png)

code 
```
.. math::

    \tilde v_j & = s(\tilde \theta_j, \mu_j) + \beta \tilde v_{j+1} \\
    & \geq s(\tilde \theta_j, 0) + \beta v_0^A \quad \forall j \geq 0

```

**Comment by fkazemian** [comment] 2018-09-05 01:52
(chang_credible)

![screenshot from 2018-09-05 10-55-10](https://user-images.githubusercontent.com/20714542/45066437-cef44a00-b101-11e8-9db8-f9004ce681c4.png)
```
The government faces a sequence of budget constraints with time
:math:`t` component

.. math:: - x_t = q_t (M_t - M_{t-1})
```
![screenshot from 2018-09-05 10-55-30](https://user-images.githubusercontent.com/20714542/45066478-f814da80-b101-11e8-9a40-7e44a514dd19.png)

```
.. math::

   \mathcal{L} & = \max_{\vec c, \vec M} 
   \min_{\vec \lambda, \vec \mu} \sum_{t=0}^\infty \beta^t
   \bigl\{ u(c_t) + v(M_t q_t)
   + \lambda_t [ y_t - c_t - x_t + q_t M_{t-1} - q_t M_t ]  \\
   & \quad \quad \quad  + \mu_t [\bar m - q_t  M_t] \bigr\}

First-order conditions with respect to :math:`c_t` and :math:`M_t`, respectively, are

.. math::

   u'(c_t) & = \lambda_t \\
   q_t [ u'(c_t) - v'(M_t q_t) ] & \leq \beta u'(c_{t+1}) 
   q_{t+1} , \quad = \ {\rm if} \ M_t q_t < \bar m
```

![screenshot from 2018-09-05 10-56-35](https://user-images.githubusercontent.com/20714542/45066508-1549a900-b102-11e8-8052-acf62eb525d1.png)

```
* A recursive representation of a credible government policy is a pair of 
  initial conditions :math:`(w_0, \theta_0)` and a five-tuple of functions

 .. math::
    h(w_t, \theta_t), m(h_t, w_t, \theta_t), x(h_t, w_t, \theta_t), \chi(h_t, w_t, \theta_t),\Psi(h_t, w_t, \theta_t)

 mapping :math:`w_t,\theta_t` and in some cases :math:`h_t` into 
 :math:`\hat h_t, m_t, x_t, w_{t+1}`, and :math:`\theta_{t+1}`, respectively

```

**Comment by fkazemian** [comment] 2018-09-05 02:39
(chang_ramsey)
![screenshot from 2018-09-05 12-10-11](https://user-images.githubusercontent.com/20714542/45067922-842a0080-b108-11e8-8fb3-fa8995a58a42.png)

```
.. math::

   \mathcal{L} & = \max_{\vec c, \vec M}
   \min_{\vec \lambda, \vec \mu} \sum_{t=0}^\infty \beta^t
   \bigl\{ u(c_t) + v(M_t q_t)
   + \lambda_t [ y_t - c_t - x_t + q_t M_{t-1} - q_t M_t ]  \\
   & \quad \quad \quad  + \mu_t [\bar m - q_t  M_t] \bigr\}

```

```
.. math::

   u'(c_t) & = \lambda_t \\
   q_t [ u'(c_t) - v'(M_t q_t) ] & \leq \beta u'(c_{t+1})
   q_{t+1} , \quad = \ {\rm if} \ M_t q_t < \bar m

```

![screenshot from 2018-09-05 12-09-11](https://user-images.githubusercontent.com/20714542/45067924-84c29700-b108-11e8-8f47-c4ca48bc29ac.png)
```
The government faces a sequence of budget constraints with time
:math:`t` component

.. math:: - x_t = q_t (M_t - M_{t-1})
```

**Comment by fkazemian** [comment] 2018-09-05 04:11
(classical_filtering)
![screenshot from 2018-09-05 13-57-31](https://user-images.githubusercontent.com/20714542/45070625-88104f80-b115-11e8-91de-2a77443fdf6f.png)

```
.. math::

    (1-\lambda_1 L) \ldots (1-\lambda_m L) y_t
    =
    \sum^m_{j=1} A_j
     \left[
         \frac{1-\beta \lambda_j \, c (\beta \lambda_j) L^{-1} c(L)^{-1} }
         { 1-\beta \lambda_j L^{-1} }
     \right] a_t

```

**Comment by fkazemian** [comment] 2018-09-05 05:26
(discrete_dp)
![screenshot from 2018-09-05 15-18-09](https://user-images.githubusercontent.com/20714542/45072796-e04c4f00-b11f-11e8-976a-13df83ae38bd.png)

```
    .. math::

            \mathit{SA} := \{(s, a) \mid s \in S, \; a \in A(s)\}

```

![screenshot from 2018-09-05 15-19-11](https://user-images.githubusercontent.com/20714542/45072831-05d95880-b120-11e8-8fe2-e9926f04ef1d.png)

 ```
   .. math::

        v(s) = \max_{a \in A(s)} 
         \left\{
             r(s, a) + \beta \sum_{s' \in S} v(s') Q(s, a, s') 
         \right\}
        \qquad (s \in S),

```

**Comment by fkazemian** [comment] 2018-09-07 00:48
(dyn_stack)

![screenshot from 2018-09-07 10-29-49](https://user-images.githubusercontent.com/20714542/45192332-24a82e00-b28b-11e8-9c9d-53f8aa82d140.png)
```
.. math::

    \mu_t
    =
    \left[\begin{array}{c}
    \mu_{zt} \\
    \mu_{xt}
    \end{array}
    \right]

```
![screenshot from 2018-09-07 10-29-21](https://user-images.githubusercontent.com/20714542/45192336-283bb500-b28b-11e8-934f-98ea45c3c940.png)
```
.. math::

    P
    =
    \left[
    \begin{array}{cc}
        P_{11} & P_{12} \\
        P_{21} & P_{22}
    \end{array}
    \right]

```
![screenshot from 2018-09-07 10-29-00](https://user-images.githubusercontent.com/20714542/45192338-2a057880-b28b-11e8-984e-740cdf8cbe37.png)

```
.. math::

    - y' P y = {\rm max}_{  u, y^*} \left\{ -  y' R y -   u'Q     u - \beta y^{* \prime} P y^* \right\}
```

**Comment by fkazemian** [comment] 2018-09-07 01:06
(estspec)
![screenshot from 2018-09-07 10-59-37](https://user-images.githubusercontent.com/20714542/45192791-dea09980-b28d-11e8-8d60-31c13944247c.png)
```
.. math::

    n I(\omega_j)
    =  \sum_{t=0}^{n-1} (X_t - \bar X)^2
    + 2 \sum_{k=1}^{n-1} \sum_{t=k}^{n-1} (X_t - \bar X)(X_{t-k} - \bar X)
    \cos(\omega_j k)

```

![screenshot from 2018-09-07 10-59-51](https://user-images.githubusercontent.com/20714542/45192794-e2ccb700-b28d-11e8-8b4a-e42586d1c3ae.png)
```
.. math::

    I(\omega_j)
    =  \hat \gamma(0)
    + 2 \sum_{k=1}^{n-1} \hat \gamma(k) \cos(\omega_j k)

```

**Comment by fkazemian** [comment] 2018-09-07 03:35
(hist_dep_policies)
![screenshot from 2018-09-07 13-26-15](https://user-images.githubusercontent.com/20714542/45197016-790ad800-b2a2-11e8-8613-8710eb5600bb.png)
```
.. math::

    v(Q_t,\tau_t,u_t)
    =
    \max_{\tau_{t+1}}
        \left\{
            A_0 Q_t-\frac {A_1}2 Q_t^2-\frac d2 u_t^2+\mu\tau_tQ_t
                + \beta v(Q_{t+1},\tau_{t+1},u_{t+1})
        \right\}
```
```
.. math::

    u_{t+1}
    =
    -\frac{A_0}d+\frac{A_1}d Q_t
        +  \frac{A_1}d+\frac1\beta u_t+\frac1d \tau_{t+1}
```
![screenshot from 2018-09-07 13-26-27](https://user-images.githubusercontent.com/20714542/45197059-9dff4b00-b2a2-11e8-8944-3d284fc774b8.png)
```
.. math::

    y_t =
        \begin{bmatrix}
            1
            \\
            Q_t
            \\
            \tau_t
            \\
            u_t
        \end{bmatrix}
        =
        \begin{bmatrix}
            z_t
            \\
            u_t
        \end{bmatrix},
```
![screenshot from 2018-09-07 13-26-51](https://user-images.githubusercontent.com/20714542/45197069-ae172a80-b2a2-11e8-8f8e-94e8b8feb21b.png)
```
.. math::

    P
    =
    \begin{bmatrix}
        P_{11}&P_{12}
        \\
        P_{21}&P_{22}
    \end{bmatrix}



```
```
.. math::

    0
    =
    \frac{\partial}{\partial u_0}
        \left(
            z_0'P_{11}z_0+z_0'P_{12}u_0+u_0'P_{21}z_0 +u_0' P_{22} u_0
        \right)
    =
    P_{12}'z_0+P_{21}z_0+2P_{22}u_0


```

```
.. math::
    :label: ES_u0

    u_0 = -P_{22}^{-1}P_{21}z_0
```


```
.. math::

    \tau_{t+1}
    =
    -F
    \begin{bmatrix}
        z_t
        \\
        u_t
    \end{bmatrix}
    \quad \text{and} \quad
    \begin{bmatrix}
        z_{t+1}
        \\
        u_{t+1}
    \end{bmatrix}
    =
    (A-BF)
    \begin{bmatrix}
        z_t
        \\
        u_t
    \end{bmatrix}
```

**Comment by fkazemian** [comment] 2018-09-07 05:14
lake_model
![screenshot from 2018-09-07 15-03-07](https://user-images.githubusercontent.com/20714542/45199735-a52d5580-b2b0-11e8-8784-159df730c9d7.png)
code:
```
.. math::

    E_{t+1} = (1-d)(1-\alpha)E_t + (1-d)\lambda U_t
```

```
.. math::

    U_{t+1} = (1-d)\alpha E_t + (1-d)(1-\lambda)U_t + b (E_t+U_t)

```

```

.. math::

    N_{t+1} = (1+b-d)N_t = (1+g)N_t
```

**Comment by fkazemian** [comment] 2018-09-10 01:03
(linear_models)
![screenshot from 2018-09-10 10-59-18](https://user-images.githubusercontent.com/20714542/45271272-19523e00-b4e9-11e8-828e-17f2245e88a7.png)
```
.. math::

    x_{t+j} = A^j x_t + A^{j-1} C w_{t+1} + A^{j-2} C w_{t+2}
    + \cdots + A^0 C w_{t+j}

```

**Comment by fkazemian** [comment] 2018-09-10 01:27
(lln_clt)
![screenshot from 2018-09-10 11-23-23](https://user-images.githubusercontent.com/20714542/45271727-57049600-b4ec-11e8-9775-2a05b44417bc.png)

```

.. math::

    \mathbb E [\mathbf X]
    :=
    \left(
    \begin{array}{c}
        \mathbb E [X_1] \\
        \mathbb E [X_2] \\
        \vdots \\
        \mathbb E [X_k]
    \end{array}
    \right)
    =
    \left(
    \begin{array}{c}
        \mu_1 \\
        \mu_2\\
        \vdots \\
        \mu_k
    \end{array}
    \right)
    =: \boldsymbol \mu

```
```
.. math::

    \Var[\mathbf X]
    =
    \left(
    \begin{array}{ccc}
        \mathbb E [(X_1 - \mu_1)(X_1 - \mu_1)]
            & \cdots & \mathbb E [(X_1 - \mu_1)(X_k - \mu_k)] \\
        \mathbb E [(X_2 - \mu_2)(X_1 - \mu_1)]
            & \cdots & \mathbb E [(X_2 - \mu_2)(X_k - \mu_k)] \\
        \vdots & \vdots & \vdots \\
        \mathbb E [(X_k - \mu_k)(X_1 - \mu_1)]
            & \cdots & \mathbb E [(X_k - \mu_k)(X_k - \mu_k)] \\
    \end{array}
    \right)
```

**Comment by fkazemian** [comment] 2018-09-10 01:27
(sorry, instead of comment I pressed close and comment)

**Comment by fkazemian** [comment] 2018-09-10 02:16
lqcontrol
![screenshot from 2018-09-10 11-51-41](https://user-images.githubusercontent.com/20714542/45272895-3db31800-b4f3-11e8-9998-0b0f21abb12e.png)
```
The following figure was computed using :math:`r = 0.05, \beta = 1 / (1
+ r), \bar c = 2,  \mu = 1, \sigma = 0.25, T = 45` and :math:`q = 10^6`
```

**Comment by fkazemian** [comment] 2018-09-10 05:54
(lqramsey)
![screenshot from 2018-09-10 15-41-59](https://user-images.githubusercontent.com/20714542/45278689-a4472e80-b511-11e8-8fc6-dc885d55190e.png)
```
.. math::

    - (c_t - b_t ) + \lambda [- \ell_t + (g_t + s_t )] = \mu_t

```

**Comment by fkazemian** [comment] 2018-09-10 06:15
lucas_model
![screenshot from 2018-09-10 16-08-34](https://user-images.githubusercontent.com/20714542/45279491-a9f24380-b514-11e8-961e-d303dbe4ac9a.png)

```
.. math::

    \begin{aligned}
        |Tf(y) - Tg(y)|
        & = \left| \beta \int f[G(y, z)] \phi(dz)
            -  \beta \int g[G(y, z)] \phi(dz) \right|
        \\
        & \leq \beta \int \left| f[G(y, z)] -  g[G(y, z)] \right| \phi(dz)
        \\
        & \leq \beta \int \| f -  g \| \phi(dz)
        \\
        & = \beta  \| f -  g \|
    \end{aligned}
```

**Comment by fkazemian** [comment] 2018-09-11 05:59
(mle)
![screenshot from 2018-09-11 10-26-49](https://user-images.githubusercontent.com/20714542/45340849-9958d080-b5db-11e8-80d0-07f272c7c28d.png)


```
.. math::


   \frac {\partial^2 \log \mathcal{L}} {\partial \boldsymbol{\beta} \partial \boldsymbol{\beta}'} =
   - \sum_{i=1}^n \phi (\mathbf{x}_i' \boldsymbol{\beta})
   \Big[
   y_i \frac{ \phi (\mathbf{x}_i' \boldsymbol{\beta}) + \mathbf{x}_i' \boldsymbol{\beta} \Phi (\mathbf{x}_i' \boldsymbol{\beta}) } { [\Phi (\mathbf{x}_i' \boldsymbol{\beta})]^2 }
   +
   (1 - y_i) \frac{ \phi_i (\mathbf{x}_i' \boldsymbol{\beta}) - \mathbf{x}_i' \boldsymbol{\beta} (1 - \Phi (\mathbf{x}_i' \boldsymbol{\beta})) } { [1 - \Phi (\mathbf{x}_i' \boldsymbol{\beta})]^2 }
   \Big]
   \mathbf{x}_i \mathbf{x}_i'

```

**Comment by fkazemian** [comment] 2018-09-11 06:10
multiplicative_functionals
![screenshot from 2018-09-11 16-01-10](https://user-images.githubusercontent.com/20714542/45341225-336d4880-b5dd-11e8-9664-ce3a20a2c5e8.png)
```
.. math::

    x_{t+1} = \left(A - B F^{-1}D \right)x_t 
        + B F^{-1} \left(y_{t+1} - y_t \right),
```

**Comment by fkazemian** [comment] 2018-09-12 00:41
perm_income:
![screenshot from 2018-09-12 10-36-14](https://user-images.githubusercontent.com/20714542/45395178-3cf7be80-b678-11e8-8f2d-80ee37d08e53.png)
```

.. math::

     \max_{b_1}
     \left\{
         u \left(\frac{b_1}{R} - b_0 + y_0 \right)
         + \beta \, \mathbb{E}_0 [ u (y_1 - b_1) ]
    \right\}

```
![screenshot from 2018-09-12 10-35-35](https://user-images.githubusercontent.com/20714542/45395197-56990600-b678-11e8-87a6-77f3a990a7d2.png)

```
.. math::

    \begin{bmatrix}
      z_{1 t+1} \\
      z_{2t+1}
    \end{bmatrix}
    =
    \begin{bmatrix}
      1 & 0 \\
      0 & 0
    \end{bmatrix}
    \begin{bmatrix}
      z_{1t} \\
      z_{2t}
    \end{bmatrix}
    + \begin{bmatrix}
          \sigma_1 & 0 \\
          0 & \sigma_2
      \end{bmatrix}
      \begin{bmatrix}
          w_{1t+1} \\
          w_{2t+1}
      \end{bmatrix}

```

**Comment by fkazemian** [comment] 2018-09-12 00:47
perm_income_cons
![screenshot from 2018-09-12 10-42-53](https://user-images.githubusercontent.com/20714542/45395366-2b62e680-b679-11e8-9eac-1a8f7d80bca1.png)
```
.. math::

    x_t := 
        \begin{bmatrix}
            z_t \\
            b_t
        \end{bmatrix}
        =
        \begin{bmatrix}
            1 \\
            y_t \\
            y_{t-1} \\
            b_t
        \end{bmatrix}

```

**Comment by fkazemian** [comment] 2018-09-12 02:54
rob_markov_perf
![screenshot from 2018-09-12 12-19-55](https://user-images.githubusercontent.com/20714542/45399313-eb0c6400-b68a-11e8-9488-425fcf1b7253.png)
```

.. math::

   \sum_{t=t_0}^{t_1 - 1}
   \beta^{t - t_0}
   \left\{
       x_t' R_i x_t
       + u_{it}' Q_i u_{it}
       + u_{-it}' S_i u_{-it}
       + 2 x_t' W_i u_{it}
       + 2 u_{-it}' M_i u_{it}
   \right\}
```

**Comment by fkazemian** [comment] 2018-09-12 03:14
robustness:
![screenshot from 2018-09-12 13-02-03](https://user-images.githubusercontent.com/20714542/45399926-5d7e4380-b68d-11e8-9b26-0af73f7990a9.png)
```

.. math::

    \hat  P
     =
     R + \hat F' Q \hat F
     + \beta (A - B \hat F)' \hat P C
       (\theta I - C' \hat P C)^{-1} C' \hat P (A - B \hat F)
       + \beta (A - B \hat F)' \hat P (A - B \hat F)
```
```

.. math::

    R + \hat F' Q \hat F
    + \beta (A - B \hat F)' \mathcal D(\hat P) (A - B \hat F)
```
![screenshot from 2018-09-12 13-00-48](https://user-images.githubusercontent.com/20714542/45399977-928a9600-b68d-11e8-8e48-09e1aa876615.png)
```
.. math::

    J_F(x)
    =
    \max_{\psi \in \mathcal P}
    \left\{
        x' (R + F'QF) x + \beta \,
        \left[
        \int J_F ( (A - BF)x + C w) \, \psi(dw) - \theta D_{KL}(\psi, \phi)
        \right]
    \right\}
```
```

.. math::

    x' P_F x + d_F
    =
    x' (R + F'QF) x + \beta \,
    \left[
     x' (A - BF)' \mathcal D(P_F) (A - BF) x + d_F + \kappa(\theta, P_F)
    \right]
```

**Comment by fkazemian** [comment] 2018-09-12 04:09
smoothing
![screenshot from 2018-09-12 14-01-44](https://user-images.githubusercontent.com/20714542/45401708-51967f80-b695-11e8-872c-c919d1f66691.png)
```
.. math::

    - \sum_{t=0}^\infty \beta^t ( c_t - \gamma)^2, \quad 0 < \beta < 1   

```
![screenshot from 2018-09-12 13-59-17](https://user-images.githubusercontent.com/20714542/45401742-6e32b780-b695-11e8-9f6e-9d973a1d5d9a.png)
```
.. math::

    \begin{bmatrix} 
       b(\bar s_1) \cr b(\bar s_2) 
    \end{bmatrix} + 
    \begin{bmatrix}  
    \bar c \cr \bar c 
    \end{bmatrix} 
    = 
    \begin{bmatrix} 
        y(\bar s_1) \cr y(\bar s_2) 
    \end{bmatrix} 
    + \beta 
    \begin{bmatrix} 
        P_{11} & P_{12} \cr P_{21} & P_{22} 
    \end{bmatrix} 
    \begin{bmatrix} 
        b(\bar s_1) \cr b(\bar s_2)  
    \end{bmatrix}   

```

**Comment by fkazemian** [comment] 2018-09-12 04:30
stationary_densities
![screenshot from 2018-09-12 14-14-13](https://user-images.githubusercontent.com/20714542/45402301-527ce080-b698-11e8-902d-547ef5170432.png)


```
.. only:: html

    In fact much stronger convergence results are true (see, for example, :download:`this paper </_static/pdfs/ECTA6180.pdf>`)

.. only:: latex

    In fact much stronger convergence results are true (see, for example, `this paper <https://lectures.quantecon.org/_downloads/ECTA6180.pdf>`__)

```

**Comment by fkazemian** [comment] 2018-09-12 04:50
wald_friedman
![screenshot from 2018-09-12 14-47-55](https://user-images.githubusercontent.com/20714542/45402822-0bdcb580-b69b-11e8-8a5a-02d766edc15e.png)
```
    .. math::

        \frac{ f_1(z_1) \cdots f_1(z_n)}{f_0(z_1) \cdots f_1(z_n)} \geq k 
    
```
![screenshot from 2018-09-12 14-45-43](https://user-images.githubusercontent.com/20714542/45402833-244cd000-b69b-11e8-90e0-55d6e0efe62b.png)

**Comment by DrDrij** [comment] 2018-09-12 14:08
Thanks for all the testing here @fkazemian.

Appears there are a few different issues identified, some repeated. eg. Matrix don't seem to render at all?

There is also an issue with only html and only latex being ignored.

@fkazemian Could you give a very brief summary of your findings from above?

**Comment by mmcky** [comment] 2018-09-13 01:30
@fkazemian regarding `arellano` it appears that the generated notebook is OK but the `nbconvert` step to html is causing the malformed equation. @DrDrij would you mind looking into this? I will slack the current arellano.ipynb file that is generated from the latest jupinx extension. 

- [ ] @DrDrij to investigate why this notebook is not converting properly via `nbconvert`

**Comment by mmcky** [comment] 2018-09-13 01:34
This is what is happening specifically for that equation in the html output

```html
<p>Expressed recursively, the value of defaulting is</p>
<p>$$
v_d(y) = u(h(y))</p>

<pre><code>+ \beta \int \left\{
        \theta v(0, y') + (1 - \theta) v_d(y')
        \right\}
        p(y, y') dy'
</code></pre>
<p>$$</p>
```

**Comment by mmcky** [comment] 2018-09-13 01:38
This is the markdown generated by jupinx

```markdown
Expressed recursively, the value of defaulting is

$$
v_d(y) = u(h(y))
    + \beta \int \left\{
            \theta v(0, y') + (1 - \theta) v_d(y')
            \right\}
            p(y, y') dy'
$$

The value of paying is

$$
v_c(B, y) = \max_{B' \geq -Z}
       \left\{
            u(y - q(B', y) B' + B)
            + \beta \int v(B', y') p(y, y') dy'
      \right\}
$$
```

I wonder if nbconvert has an issue with the spacing on the second line and ignores the `$$` as a verbatim environment

**Comment by mmcky** [comment] 2018-09-13 01:41
https://github.com/jupyter/nbconvert/issues/404

**Comment by mmcky** [comment] 2018-09-13 01:49
Good news! -- it looks like this equation issue for `arellano` is fixed using `nbconvert>=5.4.0`. @fkazemian I will rebuilt the lectures now.

**Comment by mmcky** [comment] 2018-09-13 02:07
``calvo`` is a bigger issue. It looks like `mathjax` doesn't like to parse inside of an `html` table?

The equation not rendering properly is outputted as `html`. If my diagnosis is correct - @DrDrij is there a way to get mathjax to parse inside of tables. 

```html
<p><a id='equation-eq-old9'></a></p>
<table width=100%><tr style='background-color: #FFFFFF !important;'>
<td width=10%></td>
<td width=80%>
$$
\theta_0 & = \theta_0^* \\
\mu_t &  = b_0 + b_1 \theta_t \\
\theta_{t+1} & = d_0 + d_1 \theta_t
$$
</td><td width=10% style='text-align:center !important;'>
(9)
</td></tr></table>
```

**Comment by mmcky** [comment] 2018-09-20 09:36
@DrDrij the latest adjustments seem to have worked well for equations. Thanks! I will close this and if I spot any regressions or edge cases I will open a separate issue.

**Comment by mmcky** [comment] 2018-09-23 23:36
thanks @DrDrij I will leave this one with you to investigate this week.

**Comment by DrDrij** [comment] 2018-09-25 17:36
Troubleshooting...

So taking that MathJax code and placing it outside of a table makes no difference. The equation does not load.

`$$
\theta_0 & = \theta_0^* \\
\mu_t &  = b_0 + b_1 \theta_t \\
\theta_{t+1} & = d_0 + d_1 \theta_t
$$`

Pasting the below code from the live lectures into that table cell works fine and renders the equation.

`\[\begin{split}\theta_0 &amp; = \theta_0^* \\
\mu_t &amp;  = b_0 + b_1 \theta_t \\
\theta_{t+1} &amp; = d_0 + d_1 \theta_t\end{split}\]`

The RST source is:

```
.. math::
    :label: eq_old9

    \theta_0 & = \theta_0^* \\
    \mu_t &  = b_0 + b_1 \theta_t \\
    \theta_{t+1} & = d_0 + d_1 \theta_t
```

**Comment by mmcky** [comment] 2018-10-03 04:00
@DrDrij this doesn't seem to be a problem on the current live site so the equation LaTeX should be fine. Would you mind comparing with the current live site to see what's different at the `html` level.

**Comment by mmcky** [comment] 2018-11-06 23:50
@natashawatkins can you look through this equation and see if you can spot an issue with the latex specification. It appears to not be recognised by mathjax and the `html` sphinx writer is modifying it so that it renders on our current `html` site.

```latex
$$
\theta_0 & = \theta_0^* \\
\mu_t &  = b_0 + b_1 \theta_t \\
\theta_{t+1} & = d_0 + d_1 \theta_t
$$
```

**Comment by mmcky** [comment] 2018-11-06 23:55
@DrDrij do you know an easy way to check mathjax by entering in an equation? Is there a chrome extension -- can't seem to find one.

**Comment by mmcky** [comment] 2018-11-06 23:58
Ah Got it -- I think this needs to be wrapped in an aligned for mathjax raw to work.

$$
\begin{aligned}
\theta_{0} &= \theta_{0}^* \\
\mu_t &= b_0 + b_1 \theta_t \\ 
\theta_{t+1} &= d_0 + d_1 \theta_t
\end{aligned}
$$

**Comment by mmcky** [comment] 2018-11-06 23:59
here is a good demo site: https://codepen.io/jrcharney/pen/YNYqNV

**Comment by mmcky** [comment] 2018-11-08 04:29
@fkazemian I have now recompiled the site to include fixes for this issue.

**Comment by fkazemian** [comment] 2018-11-09 04:16
Thanks @mmcky  it is fixed 


perm_income_cons
![screenshot from 2018-11-09 15-14-44](https://user-images.githubusercontent.com/20714542/48243037-414f1680-e432-11e8-902f-f7e584c5d127.png)

linear_algebra
![screenshot from 2018-11-09 15-15-50](https://user-images.githubusercontent.com/20714542/48243062-6cd20100-e432-11e8-8d7d-435dce68a3c2.png)

and so on.

**Closed** 2018-11-26 05:03 UTC
Labels: check-fix
