### ISSUE TITLE
'math' blocks has overlap with contex or there is no space between them (Jupinx)

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#12] opened 2018-09-03 01:38 UTC
![1](https://user-images.githubusercontent.com/20714542/44963432-c8cd6480-af6d-11e8-9fe3-879bb5d70539.png)
![2](https://user-images.githubusercontent.com/20714542/44963434-c9fe9180-af6d-11e8-8f14-414ce7945a01.png)
![3](https://user-images.githubusercontent.com/20714542/44963437-cb2fbe80-af6d-11e8-8ff0-c012f497193d.png)
(amss.html)
It seems most of the lectures have this problem.

**Comment by mmcky** [comment] 2018-09-07 05:15
@fkazemian it looks like the generated notebook is correctly formatted.

@DrDrij is it possible that our template is removing padding around math?

**Comment by DrDrij** [comment] 2018-09-12 13:54
@mmcky This looks like a quick fix. I've been able to rectify the issue by editing directly.

We had a similar issue in the past which we solved with:

`span.math {
    font-size: 0.92rem;
}`

The jupinx output uses `<span class="MathJax">` rather than the original `<span class="math">`. So adding the following fixed the rendering issue.

`span.MathJax {
    font-size: 0.92rem;
}`

Can I suggest we edit the template to load the stylesheet from http://compare-lectures.quantecon.org/ domain? I can then add little edits as each of the bugs come up.

Can you recompile the lectures with an updated template pointing the stylesheet to this address? (I see the _static directory exists on the compare domain) Attached example.


[lectures-local-css-js.tpl.zip](https://github.com/QuantEcon/lecture-source-py/files/2375429/lectures-local-css-js.tpl.zip)

**Comment by mmcky** [comment] 2018-09-13 03:03
Thanks @DrDrij I will look at this now

**Comment by DrDrij** [comment] 2018-09-18 18:47
@mmcky Added additional styles for both cases. (.MathJax and .math)

**Comment by mmcky** [comment] 2018-09-18 22:28
Thanks @DrDrij love your work!

**Comment by mmcky** [comment] 2018-09-18 22:28
- [ ] add latest styles and css to `quantecon.build.lectures` repo

**Comment by mmcky** [comment] 2018-09-20 09:39
@DrDrij the latest adjustments seem to have worked well for equations. Thanks! I will close this and if I spot any regressions or edge cases I will open a separate issue.

**Closed by mmcky** 2018-09-20 09:39 UTC
Labels: check-fix
